/// <reference types="cypress" />

    /*
        - fill fields with required test info - parking type, dates/duration
        - submit the form
        - reference calculation output 
            - is the calculated total time accurate?
            - is the final cost accurate based on parking type parameters
        - assert values to calculated total time and to final cost


    */

describe ('Valet Calculation Tests', () => {
    //$18 per day
    //$12 for five hours or less

    beforeEach(() => {
        cy.visit('https://www.shino.de/parkcalc/')
    })

    it ('30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('3 hours', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('4:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 3 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('5 hours', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('6:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 5 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    //cost changes after 5 hours
    it ('5 hours 1 minute', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('6:01')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 5 Hours, 1 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 18.00')
    })
    
    it ('12 hours', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=PM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 12 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 18.00')
    })

    it ('24 hours', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 18.00')
    })

    it ('24 hours 1 minute', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:01')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 1 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 36.00')
    })

    it ('3 days', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/14/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(3 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 54.00')
    })

    it ('1 week', () => {
        cy.get('select[id=ParkingLot]').select('Valet')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/18/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(7 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 126.00')
    })

})




describe('Short-Term Parking Calculations', () => {
    //$2.00 first hour; $1.00 each additional 1/2 hour
    //$24.00 daily maximum
    beforeEach(() => {
        cy.visit('https://www.shino.de/parkcalc/')
    })

    it ('30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('1 hour', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('1 hour 30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 1 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 3.00')
    })

    it ('12 hours', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=PM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 12 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 24.00')
    })

    it ('12 hours 30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=PM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 12 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 24.00')
    })

    it ('1 day 30 minutes', () => {
        //confirm thist first hour of 2nd day actually charges per half hour
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 25.00')
    })

    it ('1 day 1 hour', () => {
        //confirm thist first hour of 2nd day actually charges per half hour
        cy.get('select[id=ParkingLot]').select('Short')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 26.00')
    })

})




describe('Economy Parking Calculation', () => {
    //$2.00 per hour
    //$9.00 daily maximum
    //$54.00 per week (7th day free)
    beforeEach(() => {
        cy.visit('https://www.shino.de/parkcalc/')
    })

    it ('30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('4 hours', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('5:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 4 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 8.00')
    })

    it ('5 hours', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('6:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 5 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 9.00')
    })

    it ('6 hours', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('7:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 6 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 9.00')
    })
    it ('24 hours', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 9.00')
    })

    it ('1 day 1 minute', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:01')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 1 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 11.00')
    })

    it ('6 days', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 54.00')
    })

    it ('6 days 1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 54.00')
    })

    it ('7 days', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/18/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(7 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 54.00')
    })

    it ('2 weeks', () => {
        cy.get('select[id=ParkingLot]').select('Economy')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/25/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(14 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 108.00')
    })

})




describe('Long-Term Garage Parking Calculation', () => {
    //$2.00 per hour
    //$12.00 daily maximum
    //$72.00 per week (7th day free)
    beforeEach(() => {
        cy.visit('https://www.shino.de/parkcalc/')
    })

    it ('30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('4 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('5:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 4 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 8.00')
    })

    it ('5 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('6:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 5 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 10.00')
    })

    it ('6 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('7:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 6 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('7 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('8:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 7 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('24 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('1 day 1 minute', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:01')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 1 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 14.00')
    })

    it ('6 days', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 72.00')
    })

    it ('6 days 1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 72.00')
    })

    it ('7 days', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/18/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(7 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 72.00')
    })

    it ('2 weeks', () => {
        cy.get('select[id=ParkingLot]').select('Long-Garage')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/25/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(14 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 144.00')
    })

})



describe('Long-Term Surface Parking Calculation', () => {
    //$2.00 per hour
    //$10.00 daily maximum
    //$60.00 per week (7th day free)
    beforeEach(() => {
        cy.visit('https://www.shino.de/parkcalc/')
    })

    it ('30 minutes', () => {
        //ideally would store these values in a hashmap but idk how to do that in JS
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:30')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 0 Hours, 30 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 2.00')
    })

    it ('4 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('5:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 4 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 8.00')
    })

    it ('5 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('6:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 5 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 10.00')
    })

    it ('6 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('7:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 6 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 10.00')
    })

    it ('7 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('8:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(0 Days, 7 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 10.00')
    })

    it ('24 hours', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 10.00')
    })

    it ('1 day 1 minute', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/12/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:01')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(1 Days, 0 Hours, 1 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 12.00')
    })

    it ('6 days', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 60.00')
    })

    it ('6 days 1 hour', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/17/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('2:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(6 Days, 1 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 60.00')
    })

    it ('7 days', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/18/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(7 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 60.00')
    })

    it ('2 weeks', () => {
        cy.get('select[id=ParkingLot]').select('Long-Surface')
        cy.get('[id=StartingDate]')
            .clear()
            .type('02/11/2000')
        cy.get('[id=StartingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=StartingTimeAMPM][value=AM]')
            .check()    
        cy.get('[id=LeavingDate]')
            .clear()
            .type('02/25/2000')
        cy.get('[id=LeavingTime]')
            .clear()
            .type('1:00')
        cy.get('[name=LeavingTimeAMPM][value=AM]')
            .check()
        cy.get('[type = submit]')
            .click()
        cy.get('[class=BodyCopy]>b')
            .should('contain', '(14 Days, 0 Hours, 0 Minutes)')
        cy.get('span[class=SubHead]>b').invoke('text')
            .should('eq', '$ 120.00')
    })

})